### ISSUE TITLE
Title bar doesn't correspond to the picture

### ISSUE THREAD

**Issue by krebso** [artlaman/chalice-color-theme#1]
Hi!

I really enjoy this theme and I would like to make my whole vscode according to the pictures in the README. Unfortunately, when I set the theme, the title remains the same as before and does not match the colorscheme. Is it necessary to set it in `preferences.json` or should it come with the colorscheme?

Including picture, I am on MacOS Monterey 12.3.1

<img width="1374" alt="Screenshot 2022-05-27 at 12 22 40" src="https://user-images.githubusercontent.com/58729669/170681743-3beb5bcd-433f-47a4-8b6b-4c22afc87e4d.png">

Thanks for the awesome theme!
Martin

**Comment by artlaman** [comment]
Hello! Thanks for the awesome feedback. 🙂

This line may cause the issue.
```
 "window.nativeTabs": true
```
Looks like that the title bar also becomes native if this setting is enabled, so you need to either disable it or change the title bars color  in the macos settings

**Comment by krebso** [comment]
Much thanks! Applying the fix you suggested, everything works as supposed.
